# Generated by Django 4.2 on 2026-02-17 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OrderModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tracking_number', models.CharField(max_length=100, unique=True)),
                ('customer_name', models.CharField(max_length=255)),
                ('origin', models.CharField(max_length=255)),
                ('destination', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('CREATED', 'Created'), ('ASSIGNED', 'Assigned'), ('IN_TRANSIT', 'In Transit'), ('DELIVERED', 'Delivered'), ('CANCELLED', 'Cancelled')], default='CREATED', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'orders',
            },
        ),
        migrations.AddIndex(
            model_name='ordermodel',
            index=models.Index(fields=['tracking_number'], name='orders_trackin_cd5d94_idx'),
        ),
        migrations.AddIndex(
            model_name='ordermodel',
            index=models.Index(fields=['status'], name='orders_status_762191_idx'),
        ),
    ]
